# Implicit dependencies
# - actions/checkout@v2
# - ./.github/actions/install-linux-build-deps
# - ./.github/actions/install-solana
# - ./.github/actions/install-rust

name: Build Program
runs:
  using: 'composite'
  steps:
    - name: build-program
      working-directory: ./program
      run: |
        cargo +${{ env.RUST_TOOLCHAIN }} build-bpf --version
        cargo +${{ env.RUST_TOOLCHAIN }} build-bpf --bpf-out-dir target/deploy/
      shell: bash
